### PR TITLE
Make copyright holder more explicit to ease software redistribution

### PR DESCRIPTION
**Pull request by henry-nicolas**
Hello Simon,

This PR adds some details regarding copyright holder, yourself, which willl ease packaging the application into linux distributions.
I will be working on getting wlr-randr into debian and this will come as a requirement so that the package is allowed in the distribution.

Thanks in advance and best regards,

### CODE REVIEW

**Comment by emersion** [comment]
Thanks for the PR, but I don't want to add these extra license comments. I don't see why `main.c` should contain one, and I don't see the Meson variables documented anywhere.

This doesn't seem like an issue with other software I maintain, like Sway/wlroots/mako/slurp/etc.

**Comment by henry-nicolas** [comment]
Thanks for the feedback @emersion - would have appreciated if you had left me the opportunity to reply back on your comment before closing the PR though.

I do not see either your name or your username (emersion) listed anywhere in those files - I cannot provide any grant 

About the project you mentionned, I checked wlroots since it is packaged into Debian: LICENSE file has copyright holder details. In the case of wlroots it only mentions Purism SPC. So I can safely conclude that you are not the copyright holder of this software?

Regards,

**Comment by emersion** [comment]
All contributors are copyright holders. It doesn't make sense to list them all. See https://www.linuxfoundation.org/blog/2020/01/copyright-notices-in-open-source-software-projects/

Purism SPC has copyright over the initial code.

**Comment by emersion** [comment]
I'd merge a PR adding "The wlr-randr Contributors" to LICENSE, if that helps.

**Comment by henry-nicolas** [comment]
Sure, thanks for the suggestion - I will make such a PR. Would it be ok if I add the years as well ?

**Comment by emersion** [comment]
Only 2019 please - I don't want to update the copyright each year.

**Pull request closed without merging**
